### ISSUE TITLE
Feature: `write_xdf()` function.

### ISSUE THREAD

**Issue by abcsds** [cbrnr/XDF.jl#6]
I think this is a long term feature, but sounds doable to me. What do you think?

**Comment by cbrnr** [comment]
I'm not sure if anyone would want to write data as XDF. Apart from being a great format for streaming synchronized data, I don't think XDF is particularly well suited for storing data after these issues have been taken care of. Do you have a particular use case in mind? Because IMO just being able to write XDF is probably not worth it.

**Comment by abcsds** [comment]
Oh I get it now! Of course my motivation was to be able to write an xdf file in a programmatic way. Say I had different experiments running in a lab and I needed to store them, but of course for that exists [LSL.jl](https://github.com/samuelpowell/LSL.jl). One can send and receive data through the streams and store the data in any format.

Thanks!
